import Head from 'next/head'
import NavigationApp from './Navigation'

export default function HeadAPP(){
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationApp />
    </>
  )
}